name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main # Укажите основную ветку, из которой будет происходить деплой

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Укажите подходящую версию Node.js

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: npm ci

      # Шаг 4: Сборка проекта
      - name: Build Docusaurus site
        run: npm run build

      # Шаг 5: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
